version: '3'

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: form-builder
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
